[package]
name = "kiro-audio-graph"
version = "0.1.0"
authors = ["Christian Perez Llamas"]
edition = "2018"

[dependencies]
thiserror = "^1.0"
derive_more = { version = "0.99.11", default-features = false, features = ["display"] }

