[package]
name = "kiro-audio-engine"
version = "0.1.0"
authors = ["Christian Perez Llamas"]
edition = "2018"

[dependencies]
kiro-audio-graph = { path = "../kiro-audio-graph" }
kiro-audio-driver = { path = "../kiro-audio-driver" }

thiserror = "^1.0"
anyhow = "^1.0"
ringbuf = "0.2.2"